### ISSUE TITLE
provide contact info

### ISSUE THREAD

**Issue by jimmac** [containers/containertoolbx.org#2]
- mailing list, twitter, repo, chat irc/matrix

**Comment by debarshiray** [comment]
I suppose you want to do something like [flatpak.org/about](https://flatpak.org/about/)?

Right now we have:
* Twitter: https://twitter.com/containertoolbx
* Matrix: [#toolbx:matrix.org](https://matrix.to/#/#toolbx:matrix.org)
* Git: https://github.com/containers/toolbox

While we (specifically @HarryMichal) are working on registering the `toolbx` namespace on Libera.Chat, it's going to take a few more months, and we should probably encourage people to use Matrix directly. So it might be wise to not advertise IRC. ;)

I think it will be useful to have a *Toolbx History* section like we have for Flatpak. If you want I can write up the content.

**Comment by debarshiray** [comment]
Our private mailing list for security issues is `security@lists.podman.io`.

The entire security policy is described [here](https://github.com/containers/toolbox/blob/main/SECURITY.md), which redirects to [this](https://github.com/containers/common/blob/main/SECURITY.md) document.

**Comment by debarshiray** [comment]
The security contact needs to be added.
