### ISSUE TITLE
Logo specimen PDF contains old logo

### ISSUE THREAD

**Issue by jimmac** [containers/containertoolbx.org#31]
Major oversight on my part.

![Screenshot from 2022-12-02 10-30-01](https://user-images.githubusercontent.com/14821/205261169-f420833f-e11e-48c9-a843-3d04007068f1.png)

**Comment by debarshiray** [comment]
Thanks, @jimmac 

My jaded plebeian eyes are failing to spot the obvious difference, but I am really happy that you keep an eye on these things.  :)
