### ISSUE TITLE
Improve site structure

### ISSUE THREAD

**Issue by jimmac** [containers/containertoolbx.org#40]
The site has been built on the premise the content is very sparse and has grown the initial one simple page size. It would be nice to redesign and restructure it for the gained amount of content.

The top level goals should remain to:

- [x] Explain what toolbx is
- [x] Provide common use cases it covers
- [x] Show supported distros (now that it's not just Fedora and RHEL)
- [x] Ouline how to contribute 
- [ ] Potentially expose more of the documentation/man pages.

### Styling polish
- [ ] Extra wide layout
- [x] All illustrations for light/dark mode
- [x] Additional content is asking for footer navigation
- [ ] Provide non-animated variants of illustrations for `prefers-reduced-motion`
- [x] Font optimizations (stylesheet only woff2 hosting).

**Comment by jimmac** [comment]
Debarshi suggested special casing super wide layout. I'd just do multicolumn using media question.

**Comment by debarshiray** [comment]
> Debarshi suggested special casing super wide layout. I'd just do multicolumn using media queries.

*Suggested* is a strong word.  :)

I leave the final choice to you.  Whatever you decide is fine with me.
